In [1]:


import pandas as pd

import json
import re
import warnings

In [2]:
df = pd.read_csv('/home/plantgenomics/WDU/downloads/AraNet.csv',sep='\t') #아라넷 ->DF

In [3]:
df2 = df.groupby(["source","target"]).size().reset_index() #source,target만 가져옴.

In [4]:
df100=df

In [5]:
df100.head()

      source     target     count
0  AT2G33370  AT4G34555  5.363809
1  AT1G04480  AT4G34555  5.362964
2  AT2G27530  AT4G16720  5.362912
3  AT3G60245  AT5G58420  5.361639
4  AT3G60245  AT4G34555  5.361599

In [6]:
selected_genelist=['AT1G73590', 'AT2G14960', 'AT2G39370', 'AT3G19200'] #예진이가 만들어준 옥신관련유전자4개

In [7]:
df100['source_test'] = df.apply(lambda x : x['source'] in set(selected_genelist),axis=1) #4개포함된것 찾
df100['target_test'] = df.apply(lambda x : x['target'] in set(selected_genelist),axis=1) #4개포함된것 찾

In [10]:
mm1 = df100['source_test'] == False #마아아스킹
mm2 = df100['target_test'] == False #마아아스킹
mm = mm1&mm2 #마아아스킹 &마아아스킹

In [12]:
df100[~mm] #df100에서 마스킹.

           source     target     count  source_test  target_test
37473   AT1G59500  AT2G14960  4.646981        False         True
38700   AT1G28130  AT2G14960  4.619654        False         True
40914   AT2G14960  AT4G37390  4.569168         True        False
42123   AT2G39370  AT3G58190  4.542752         True        False
53814   AT2G23170  AT2G39370  4.390975        False         True
84712   AT1G73590  AT5G65980  4.227925         True        False
84713   AT1G73590  AT5G01990  4.227925         True        False
84714   AT1G73590  AT2G17500  4.227925         True        False
84715   AT1G73590  AT1G76530  4.227925         True        False
84716   AT1G73590  AT1G76520  4.227925         True        False
84722   AT1G71090  AT1G73590  4.227925        False         True
84740   AT1G20925  AT1G73590  4.227925        False         True
107142  AT2G39370  AT4G27260  4.083999         True        False
119666  AT1G25490  AT1G73590  3.968576        False         True
124575  AT1G73590  AT2G36910  3.920609         True        False
126735  AT1G48690  AT2G14960  3.908274        False         True
129255  AT1G73590  AT3G28860  3.881988         True        False
129256  AT1G73590  AT2G34650  3.881988         True        False
132944  AT2G33310  AT2G39370  3.833151        False         True
149433  AT3G19200  AT5G54490  3.671775         True        False
165482  AT2G14960  AT2G47750  3.501352         True        False
174827  AT1G73590  AT2G26180  3.400187         True        False
209927  AT2G39370  AT3G29720  3.003993         True        False
209928  AT2G39370  AT3G29680  3.003993         True        False
221222  AT2G39370  AT4G14560  2.888293         True        False
223656  AT2G14960  AT3G58190  2.857695         True        False
229106  AT2G14960  AT5G25890  2.800537         True        False
241088  AT2G39370  AT5G54510  2.689088         True        False
247480  AT2G14960  AT2G23170  2.630156         True        False
248349  AT2G39370  AT3G15540  2.621262         True        False
...           ...        ...       ...          ...          ...
660228  AT2G14960  AT2G36220  1.043965         True        False
664082  AT2G39370  AT2G42440  1.040076         True        False
678064  AT3G19200  AT4G22620  1.026321         True        False
720342  AT3G19200  AT4G37590  0.991908         True        False
724054  AT2G14960  AT3G60550  0.985298         True        False
726658  AT1G15580  AT2G39370  0.980175        False         True
731157  AT2G14960  AT2G34400  0.971730         True        False
736794  AT1G73590  AT2G26760  0.962120         True        False
740208  AT2G14960  AT4G27260  0.955342         True        False
756387  AT1G21980  AT3G19200  0.926985        False         True
763342  AT1G19220  AT3G19200  0.914292        False         True
770097  AT1G73590  AT5G63670  0.902383         True        False
782561  AT1G07700  AT2G14960  0.882319        False         True
795153  AT1G73590  AT4G17350  0.864251         True        False
795750  AT2G39370  AT3G19200  0.863287         True         True
796238  AT1G19220  AT2G39370  0.862491        False         True
798033  AT1G68400  AT1G73590  0.859605        False         True
808219  AT2G14960  AT4G30280  0.843745         True        False
821363  AT3G19200  AT5G59330  0.824680         True        False
824727  AT2G39370  AT3G49700  0.819903         True        False
843470  AT2G39370  AT4G22620  0.794482         True        False
846779  AT1G58340  AT1G73590  0.789739        False         True
852568  AT2G14960  AT4G14560  0.781006         True        False
854359  AT2G14960  AT4G37290  0.778306         True        False
857454  AT1G73590  AT2G40540  0.773834         True        False
859673  AT2G39370  AT3G05900  0.770617         True        False
865547  AT3G19200  AT5G26930  0.762102         True        False
867955  AT1G73590  AT1G75640  0.758720         True        False
869910  AT2G14960  AT5G01440  0.755902         True        False
871094  AT1G73590  AT2G26710  0.754257         True        False

[92 rows x 5 columns]

In [14]:
df200 = df100[~mm].groupby(["source","target"]).size().reset_index() #source,target항목만 df200으로 만듬

In [19]:
udu = list(set(list(df100[~mm]['source']) + list(df100[~mm]['target'])))

In [20]:
group_dict100 = {}
counter = 0
for gene in udu:
    what_gene = re.match("^(\D)(\D)(\d)(\D)(\d)(\d)(\d)(\d)(\d)$", gene)
    if what_gene:
        net_gene = ''.join(what_gene.group(0))
        if net_gene not in group_dict100:
            counter += 1
            group_dict100[net_gene] = counter
        else:
            pass

In [21]:
nodes_list200 = []

for gene in udu:
    what_gene2 = re.match("^(\D)(\D)(\d)(\D)(\d)(\d)(\d)(\d)(\d)$", gene)
    if what_gene2:
        net_gene2 = ''.join(what_gene2.group(0))
        nodes_list200.append({"name":gene, "group": group_dict100.get(net_gene2)})

In [15]:
unique_gen = pd.Index(df200['source']
                      .append(df200['target'])
                      .reset_index(drop=True).unique()) #source,target에서 중복없는 유전자 찾음

In [17]:
df200.rename(columns={0:'count'}, inplace=True)
temp_links_list200 = list(df200.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [18]:
links_list200 = []
for link in temp_links_list200:
    record = {"value":link['value'], "source":unique_gen.get_loc(link['source']),
     "target": unique_gen.get_loc(link['target'])}
    links_list200.append(record)

In [24]:

json_prep200= {"links":links_list200, "nodes":nodes_list200}

json_prep200.keys()
#json 형식으로 만들어버리기

dict_keys(['nodes', 'links'])

In [25]:
json_dump=json.dumps(json_prep200,indent=1, sort_keys=True)

In [26]:
filename_out='exp.json' #.json 파일 생성
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()